# MADE BY:
#  __    __                                          __        __  __  __                     
# /  |  /  |                                        /  |      /  |/  |/  |                    
# $$ |  $$ |  ______   _______    ______    ______  $$ |____  $$/ $$ |$$/   _______  __    __ 
# $$  \/$$/  /      \ /       \  /      \  /      \ $$      \ /  |$$ |/  | /       |/  |  /  |
#  $$  $$<  /$$$$$$  |$$$$$$$  |/$$$$$$  |/$$$$$$  |$$$$$$$  |$$ |$$ |$$ |/$$$$$$$/ $$ |  $$ |
#   $$$$  \ $$    $$ |$$ |  $$ |$$ |  $$ |$$ |  $$ |$$ |  $$ |$$ |$$ |$$ |$$ |      $$ |  $$ |
#  $$ /$$  |$$$$$$$$/ $$ |  $$ |$$ \__$$ |$$ |__$$ |$$ |  $$ |$$ |$$ |$$ |$$ \_____ $$ \__$$ |
# $$ |  $$ |$$       |$$ |  $$ |$$    $$/ $$    $$/ $$ |  $$ |$$ |$$ |$$ |$$       |$$    $$ |
# $$/   $$/  $$$$$$$/ $$/   $$/  $$$$$$/  $$$$$$$/  $$/   $$/ $$/ $$/ $$/  $$$$$$$/  $$$$$$$ |
#                                         $$ |                                      /  \__$$ |
#                                         $$ |                                      $$    $$/ 
#                                         $$/                                        $$$$$$/       
VERSION: "1.0.0" # Internal use only

# This is where you can list the items you want to have an effect given when consumed
# You can use any number of effects
# If you want an infinite duration for an effect, set it to 0
# Maximum amplifier for effects is 255
# See the included examples for more clarification

# Add items using this format:
# {
#     "Item-ID":[
#         [Effect-ID,Effect-Amplifier,Effect-Duration],
#         [Effect-ID,Effect-Amplifier,Effect-Duration],
#         [Effect-ID,Effect-Amplifier,Effect-Duration]
#     ],
#     "Item-ID":[
#         [Effect-ID,Effect-Amplifier,Effect-Duration],
#         [Effect-ID,Effect-Amplifier,Effect-Duration]
#     ]
# }

# Example configuration:
# {
#     "364":[ ← When steak(364) is consumed, give blindness(15) level 1 for 10 seconds and strength(5) level 2 for 30 seconds
#         [15,1,10],
#         [5,2,30]
#     ],
#     "260":[ ← When an apple(260) is consumed, give speed(1) level 3 for 15 seconds and infinite(0) night vision(16) level 1
#         [1,3,15],
#         [16,1,0]
#     ]
# }

# → → → → → Please input your configuration in the config.json file! ← ← ← ← ← 

# Here is a list of all available effects with their IDs
# ABSORPTION = 22
# BLINDNESS = 15
# CONDUIT_POWER = 26
# CONFUSION = 9
# DAMAGE_RESISTANCE = 11
# FATAL_POISON = 25
# FATIGUE = 4
# FIRE_RESISTANCE = 12
# HARMING = 7
# HASTE = 3
# HEALING = 6
# HEALTH_BOOST = 21
# HUNGER = 17
# INSTANT_DAMAGE = 7
# INSTANT_HEALTH = 6
# INVISIBILITY = 14
# JUMP = 8
# JUMP_BOOST = 8
# LEVITATION = 24
# MINING_FATIGUE = 4
# NAUSEA = 9
# NIGHT_VISION = 16
# POISON = 19
# REGENERATION = 10
# RESISTANCE = 11
# SATURATION = 23
# SLOWNESS = 2
# SPEED = 1
# STRENGTH = 5
# WATER_BREATHING = 13
# WEAKNESS = 18
# WITHER = 20