# MADE BY:
#  __    __                                          __        __  __  __                     
# /  |  /  |                                        /  |      /  |/  |/  |                    
# $$ |  $$ |  ______   _______    ______    ______  $$ |____  $$/ $$ |$$/   _______  __    __ 
# $$  \/$$/  /      \ /       \  /      \  /      \ $$      \ /  |$$ |/  | /       |/  |  /  |
#  $$  $$<  /$$$$$$  |$$$$$$$  |/$$$$$$  |/$$$$$$  |$$$$$$$  |$$ |$$ |$$ |/$$$$$$$/ $$ |  $$ |
#   $$$$  \ $$    $$ |$$ |  $$ |$$ |  $$ |$$ |  $$ |$$ |  $$ |$$ |$$ |$$ |$$ |      $$ |  $$ |
#  $$ /$$  |$$$$$$$$/ $$ |  $$ |$$ \__$$ |$$ |__$$ |$$ |  $$ |$$ |$$ |$$ |$$ \_____ $$ \__$$ |
# $$ |  $$ |$$       |$$ |  $$ |$$    $$/ $$    $$/ $$ |  $$ |$$ |$$ |$$ |$$       |$$    $$ |
# $$/   $$/  $$$$$$$/ $$/   $$/  $$$$$$/  $$$$$$$/  $$/   $$/ $$/ $$/ $$/  $$$$$$$/  $$$$$$$ |
#                                         $$ |                                      /  \__$$ |
#                                         $$ |                                      $$    $$/ 
#                                         $$/                                        $$$$$$/
VERSION: "1.1.0" # Internal use only

# This is the syntax for adding effects to items
# You can use any number of effects
# If you want an infinite duration for an effect, set it to 0
# Maximum amplifier for effects is 255
# See the included examples and format below for more clarification

# Add items using this format:
# "Item-ID:Item-Damage":
#   - [Effect-ID,Effect-Amplifier,Effect-Duration]
#   - [Effect-ID,Effect-Amplifier,Effect-Duration]
#   - [Effect-ID,Effect-Amplifier,Effect-Duration]

# These effects will be added when a player CONSUMES an item
Consumables:
  "364": # When steak(ID = 364) is consumed:
    - [15,1,10] # Give blindness(ID = 15) level 1 for 10 seconds
    - [5,2,30] # Give strength(ID = 5) level 2 for 30 seconds
  "260": # When an apple(ID = 260) is consumed:
    - [1,3,15] # Give speed(ID = 1) level 3 for 15 seconds
    - [16,1,0] # Give night vision(ID = 16) level 1 infinitely(0) 

# These effects will be added when a player INTERACTS with the item
Non-Consumables:
  "6:3": # When interacting with a jungle sapling(ID = 6:3):
    - [2,1,60] # Give slowness(ID = 2) level 1 for 60 seconds
    - [12,1,30] # Give fire resistance(ID = 12) level 1 for 30 seconds
    - [1,3,5] # Give speed(ID = 1) level 3 for 5 seconds
  "40": # When interacting with a red mushroom(ID = 40):
    - [2,1,5] # Give slowness(ID = 2) level 1 for 5 seconds

# Here's a list of all available effects with their IDs
# ABSORPTION = 22
# BLINDNESS = 15
# CONDUIT_POWER = 26
# CONFUSION = 9
# DAMAGE_RESISTANCE = 11
# FATAL_POISON = 25
# FATIGUE = 4
# FIRE_RESISTANCE = 12
# HARMING = 7
# HASTE = 3
# HEALING = 6
# HEALTH_BOOST = 21
# HUNGER = 17
# INSTANT_DAMAGE = 7
# INSTANT_HEALTH = 6
# INVISIBILITY = 14
# JUMP = 8
# JUMP_BOOST = 8
# LEVITATION = 24
# MINING_FATIGUE = 4
# NAUSEA = 9
# NIGHT_VISION = 16
# POISON = 19
# REGENERATION = 10
# RESISTANCE = 11
# SATURATION = 23
# SLOWNESS = 2
# SPEED = 1
# STRENGTH = 5
# WATER_BREATHING = 13
# WEAKNESS = 18
# WITHER = 20